services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${GOBID_DATABASE_USER}
      POSTGRES_PASSWORD: ${GOBID_DATABASE_PASSWORD}
      POSTGRES_DB: ${GOBID_DATABASE_NAME}
    ports:
      - "${GOBID_DATABASE_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local